# train.py

PUNCHLINES = [
    "Tumhara koi Naam hai ya main tumhe meri kah sakta hoon..!!",
    "Mujhe lagata hai tumse vitamine me ki kami hai ..!!",
    "Mujhe nahi pata kaun jyada sundar hai mausam ya tumhari aankhe..!!",
    "Kya tum thakti nahi ho kyunki tum mere dimag me pure din daudati rahati ho ..!!",
    "Mera name Shivu hai, Aap jaisi pari ka bhi koi nam to hoga..!!",
    "Aapke papa air force me the kya? Kyuki aap ek bam ki tarah ho..!!",
    "Main kho gaya hoon, kya tum mujhe apne dil ka pata bataogi..??",
    "Kya tum time traveler ho? Main tum me apna future dekhta hoon..!!",
    "Kya aap ek jadugar ho ? Kyunki jab bhi aapko dekhti hoon, baki sab gayab ho jata hai..!!",
    "Doctor ne advice kiya hai ki sone se pahle aapki photo dekh kar sona jaruri hai warna heart attack aa sakta hai..!!",
    "Tumhre pyar ka inverter jab se is dil main lagaya hai, tab se is dil ki battery low nahi hoti hai ..!!",
    "Agar tum aur main moje hote to behtrin jodi bante ..!!",
    "Mujhe lagata hai mere phone me kuch to gadbad hai, kya tum phone karke dekhogi ye chal raha hai ya nahi??",
    "Tumhare dil ka hotspot On hai shayad, kyuki mere dil ka wifi tumse bar bar connect ho raha hai ..!!",
    "Ab svarg kaisa hai, jab se tumne use chhoda hai ??",
    "Sexy hone ke alawa, tum jine ke liye kya karti ho ??",
    "Kya tumhare parents bakers hai ? Kyunki tum cutiepie ho…!!",
    "Main sapno ka pichha karne me vishwas rakhta hoon, kya mujhe instagram ID bataogi ..!!",
    "Tumhare dil me vacuum cleaner bhi laga hai kya?? Kyunki bahut saf dil hai tumhara ..!!",
    "Jaldi se koi bhagwan ko bulao kyuki ek pari kho gayi hai, aur wo pari yaha mere pe line mar rahi hai..!!",
    "Tum sirf mere phone ka password hi nahi, mere chehre ki smile ka bhi password ho.!!",
    "Main to sirf tumhare pyar ka nasha karta hoon, and uske hang over ke aage koi aur nashe ki jarurat nahi hai ..!!",
    "Kahte hai agar kisi chiz ko dil se chaho, to puri kayanat usse tumse milane ki koshish me lag jati hai ..!!",
    "Meri ankhon ko kuch ho gaya hai, aap par se hat hi nahi rahi hai ..!!",
    "Aapki aankhe ocean ki tarah blue hai, aur main usme har bar dub jata hoon..!!",
    "Mujhe maf karna kyunki mujhe nahi lagta ki aap aur main isse pahle kahi mile honge kyunki main itna hasin aur sundar chehra kabhi nahi bhul sakta..!!",
    "Aap itne cute ho ki agar msg na bhi karna chahu, to bhi hath khud keypad par chalne lagta hai ..!!",
    "Aapke pass naksha hai kya? Kyuki main aapki ankhon me kho gyi hoon,,!!",
    "Aap choro ke raja lagte ho, kyuki aapne mera dil chura liya hai ..!!",
    "Jaldi se mujhe koi chimti karo, kyun mujhe aisa lag raha hai ki main koi sapna dekh raha hoon,,!!",
    "Kuch log hai jo kahte hai ki Disneyland is duniya ki sabse hasin jagah hai, lagta hai shayad unhone aapki bahe nahi dekhi.!!",
    "Aap ek camere ki tarah ho jab bhi aapka photo dektha hoon, meri automatic smile aa jati hai ..!!",
    "Meri har ek sans par nam hai tumhara, aaj me khush hoon, to ye ehsas hai tumhara ..!!",
    "Tujhko lekar mera khyaal nahi badlega, saal badlega par dil ka haal nahi badlega..!!",
    "Khoobsurat hone ke alawa, tum jeene ke liye aur kya karti ho?",
    "Bhagwan ka diya sabkuch hai bas kami hai toh uski jo is sabkuch ko kharch kar sake.",
    "Kya aaspas koi airport hai ya phir mera dil tumko dekh kar ud raha hai!",
    "Kya tum pehli nazar ke pyaar mein yakeen rakhti ho ya main ek baar phir koshish karoon?",
    "Koi kamaal nahi ki aasmaan ka rang neela hai, ye rang toh tumhari aankhon ka bhi hai.",
    "Mujhe map chahiye, main tumhari aankhon mein kahin kho gaya hoon.",
    "Tumhein shayad nahi pata, lekin tum meri baahon mein bahut khoobsurat lagogi.",
    "Gulab jamun pasand hai na tumko, tabhi main sochoon tum itni sweet kyon ho.",
    "Kya tum keyboard ho? Kyunki tum bilkul mere type ki ho.",
    "Tumhare pyaar mein PhD karna chahta hoon, degree toh mil jayegi na?",
    "Chhoti si zindagi hai, tum kab tak intezaar karaogi.",
    "Tumhare papa ko papa kehne ka mann hai, kya tum raazi ho?",
    "Mohabbat mein sabkuch jayaz hai, bas chhod kar mat jaana.",
    "Hum pichhle janam mein premi the shayad, tabhi tumhari or khincha chala aata hoon.",
    "Tumhara nishana achha hai, door se bhi dekhti ho toh seedhe dil par lagta hai.",
    "Chai main bana diya karunga, bas tum kitchen mein saath khadi rehna.",
    "Zaroori nahi ki prem mein Taj Mahal banaya jaye, aap bartan dhokar bhi apni Mumtaz ko khush rakh sakte hain."
]
