# train.py

PUNCHLINES = [
    "Tumhara koi Naam hai ya main tumhe meri kah sakta hoon..!!",
    "Mujhe lagata hai tumse vitamine me ki kami hai ..!!",
    "Mujhe nahi pata kaun jyada sundar hai mausam ya tumhari aankhe..!!",
    "Kya tum thakti nahi ho kyunki tum mere dimag me pure din daudati rahati ho ..!!",
    "Mera name Shivu hai, Aap jaisi pari ka bhi koi nam to hoga..!!",
    "Aapke papa air force me the kya? Kyuki aap ek bam ki tarah ho..!!",
    "Main kho gaya hoon, kya tum mujhe apne dil ka pata bataogi..??",
    "Kya tum time traveler ho? Main tum me apna future dekhta hoon..!!",
    "Kya aap ek jadugar ho ? Kyunki jab bhi aapko dekhti hoon, baki sab gayab ho jata hai..!!",
    "Doctor ne advice kiya hai ki sone se pahle aapki photo dekh kar sona jaruri hai warna heart attack aa sakta hai..!!",
    "Tumhre pyar ka inverter jab se is dil main lagaya hai, tab se is dil ki battery low nahi hoti hai ..!!",
    "Agar tum aur main moje hote to behtrin jodi bante ..!!",
    "Mujhe lagata hai mere phone me kuch to gadbad hai, kya tum phone karke dekhogi ye chal raha hai ya nahi??",
    "Tumhare dil ka hotspot On hai shayad, kyuki mere dil ka wifi tumse bar bar connect ho raha hai ..!!",
    "Ab svarg kaisa hai, jab se tumne use chhoda hai ??",
    "Sexy hone ke alawa, tum jine ke liye kya karti ho ??",
    "Kya tumhare parents bakers hai ? Kyunki tum cutiepie ho…!!",
    "Main sapno ka pichha karne me vishwas rakhta hoon, kya mujhe instagram ID bataogi ..!!",
    "Tumhare dil me vacuum cleaner bhi laga hai kya?? Kyunki bahut saf dil hai tumhara ..!!",
    "Jaldi se koi bhagwan ko bulao kyuki ek pari kho gayi hai, aur wo pari yaha mere pe line mar rahi hai..!!",
    "Tum sirf mere phone ka password hi nahi, mere chehre ki smile ka bhi password ho.!!",
    "Main to sirf tumhare pyar ka nasha karta hoon, and uske hang over ke aage koi aur nashe ki jarurat nahi hai ..!!",
    "Kahte hai agar kisi chiz ko dil se chaho, to puri kayanat usse tumse milane ki koshish me lag jati hai ..!!",
    "Meri ankhon ko kuch ho gaya hai, aap par se hat hi nahi rahi hai ..!!",
    "Aapki aankhe ocean ki tarah blue hai, aur main usme har bar dub jata hoon..!!",
    "Mujhe maf karna kyunki mujhe nahi lagta ki aap aur main isse pahle kahi mile honge kyunki main itna hasin aur sundar chehra kabhi nahi bhul sakta..!!",
    "Aap itne cute ho ki agar msg na bhi karna chahu, to bhi hath khud keypad par chalne lagta hai ..!!",
    "Aapke pass naksha hai kya? Kyuki main aapki ankhon me kho gyi hoon,,!!",
    "Aap choro ke raja lagte ho, kyuki aapne mera dil chura liya hai ..!!",
    "Jaldi se mujhe koi chimti karo, kyun mujhe aisa lag raha hai ki main koi sapna dekh raha hoon,,!!",
    "Kuch log hai jo kahte hai ki Disneyland is duniya ki sabse hasin jagah hai, lagta hai shayad unhone aapki bahe nahi dekhi.!!",
    "Aap ek camere ki tarah ho jab bhi aapka photo dektha hoon, meri automatic smile aa jati hai ..!!",
    "Meri har ek sans par nam hai tumhara, aaj me khush hoon, to ye ehsas hai tumhara ..!!",
    "Tujhko lekar mera khyaal nahi badlega, saal badlega par dil ka haal nahi badlega..!!",
    "Khoobsurat hone ke alawa, tum jeene ke liye aur kya karti ho?",
    "Bhagwan ka diya sabkuch hai bas kami hai toh uski jo is sabkuch ko kharch kar sake.",
    "Kya aaspas koi airport hai ya phir mera dil tumko dekh kar ud raha hai!",
    "Kya tum pehli nazar ke pyaar mein yakeen rakhti ho ya main ek baar phir koshish karoon?",
    "Koi kamaal nahi ki aasmaan ka rang neela hai, ye rang toh tumhari aankhon ka bhi hai.",
    "Mujhe map chahiye, main tumhari aankhon mein kahin kho gaya hoon.",
    "Tumhein shayad nahi pata, lekin tum meri baahon mein bahut khoobsurat lagogi.",
    "Gulab jamun pasand hai na tumko, tabhi main sochoon tum itni sweet kyon ho.",
    "Kya tum keyboard ho? Kyunki tum bilkul mere type ki ho.",
    "Tumhare pyaar mein PhD karna chahta hoon, degree toh mil jayegi na?",
    "Chhoti si zindagi hai, tum kab tak intezaar karaogi.",
    "Tumhare papa ko papa kehne ka mann hai, kya tum raazi ho?",
    "Mohabbat mein sabkuch jayaz hai, bas chhod kar mat jaana.",
    "Hum pichhle janam mein premi the shayad, tabhi tumhari or khincha chala aata hoon.",
    "Tumhara nishana achha hai, door se bhi dekhti ho toh seedhe dil par lagta hai.",
    "Chai main bana diya karunga, bas tum kitchen mein saath khadi rehna.",
    "Zaroori nahi ki prem mein Taj Mahal banaya jaye, aap bartan dhokar bhi apni Mumtaz ko khush rakh sakte hain.",
    "Kya tum Google ho? Kyunki meri saari talaash tum par aakar khatam ho jati hai..!!",
    "Agar tumhara muskurana ek jurm hai, toh main umar qaid ke liye taiyaar hoon..!!",
    "Tum thak nahi jati? Pura din mere khayalon mein chalti rehti ho..!!",
    "Main time traveler toh nahi, par mujhe hamara future ek sath bohot haseen dikh raha hai..!!",
    "Log kehte hain farishte aasmaan mein hote hain, phir tum zameen par kya kar rahi ho?..!!",
    "Tumhari aankhon mein koi GPS hai kya? Main har baar inme kho jata hoon..!!",
    "Dil ki chori ki report likhwani thi, kya tum apna naam btaogi?..!!",
    "Main koi photographer toh nahi, par hum dono ki jodi ki picture perfect aayegi..!!",
    "Tumhara naam WiFi hai kya? Kyunki mujhe ek bohot strong connection feel ho raha hai..!!",
    "Agar khoobsurati ka koi tax hota, toh tum definitely bankrupt hoti..!!",
    "Kya tumhare paas band-aid hai? Kyunki tumhare pyar mein girne se mere ghutne chhil gaye hain..!!",
    "Suraj ki roshni ya tumhari muskaan? Pata nahi kaun jyada chamakta hai..!!",
    "Bhagwan ne tumhe fursat mein banaya hoga, aur phir apna master-piece chhod diya..!!",
    "Mujhe pehle lagta tha jadugar nahi hote, phir maine tumhari aankhon mein dekh liya..!!",
    "Tumhare aas-paas aate hi meri saansein kyun tez ho jati hain?..!!",
    "Log chaand ko dekhte hain, aur main sirf tumhe dekhna chahta hoon..!!",
    "Tumhari ek muskaan meri poori thakan mitane ke liye kaafi hai..!!",
    "Aisa lagta hai jaise khuda ne mere saare sapno ko tumhare roop mein sach kar diya hai..!!",
    "Mujhe apne dil ka password de do, wada karta hoon kabhi hack nahi karunga..!!",
    "Tum itni pyari ho ki mujhe dar hai kahin tumhe dekh kar mujhe diabetes na ho jaye..!!",
    "Dictionary ban banane wale ne pakka tumhe nahi dekha hoga, warna khoobsurati ka matlab tumhara naam hota..!!",
    "Tumhari awaaz sunkar mere dil ki dhadkan apna rasta bhool jati hai..!!",
    "Kya tum thodi der mere paas baithogi? Mera dil bohot shor macha raha hai tumhe dekh kar..!!",
    "Aasmaan mein sitare toh bohot hain, par meri zameen ka chaand sirf tum ho..!!",
    "Agar koi mujhse pooche ki sukoon kaisa lagta hai, toh main chup chap tumhara naam le lunga..!!",
    "Log kehte hain waqt kisi ke liye nahi rukta, shayad unhone tumhe muskurate hue nahi dekha..!!",
    "Maine suna tha jadoo sirf kahaniyon mein hota hai, phir maine tumhari aankhon mein dekh liya..!!",
    "Mujhe lagta hai police ko call karna padega, kyunki kisi ne abhi-abhi mera dhyan chura liya hai..!!",
    "Kya tumhare paas Google Maps hai? Kyunki main tumhari aakhon ki gehrai mein poori tarah kho gaya hoon..!!",
    "Doctor ne kaha tha mera dil thoda kamzor hai, aur tumne muskura kar isse aur tez dhadka diya..!!",
    "Kya mujhe ek choti si permission mil sakti hai? Aaj raat tumhare sapno mein aane ki..!!",
    "Meri life ka lens bilkul blur tha, tumhare aate hi sab kuch focus mein aa gaya..!!",
    "Tum itni sweet ho ki mujhe darr hai kahin tumse mil kar mujhe diabetes na ho jaye..!!",
    "Aasman se ek tara kam hai aaj, lagta hai wo tum hi ho..!!",
    "Yahan achanak garmi badh gayi hai, ya ye sirf tumhari smile ka asar hai..!!",
    "Tum thak nahi jati? Pura din mere dimaag mein jo ghoomti rehti ho..!!",
    "Mujhe apne dil ka address dena, lagta hai main apna dil tumhare paas bhool aaya hoon..!!",
    "Apna haath dikhana zara... mujhe check karna hai meri kismat ki lakeer tumhari lakeeron se judi hai ya nahi..!!",
    "Tumhara naam kya hai? Kyunki mujhe apni life ka naya password set karna hai..!!",
    "Lagta hai Newton galat tha, kyunki mujhe gravity nahi, tumhari kashish apni taraf kheench rahi hai..!!",
    "Aaina bhi sharma jata hoga, jab tum subah usme khud ko dekhti hogi..!!",
    "Mere dil mein ek VIP kamra khali hai, kya tum bina kiraya diye wahan shift hona chahogi..!!",
    "Meri dictionary mein 'khoobsurat' ka matlab aaj tak samajh nahi aaya tha, aaj tumhe dekh kar clear ho gaya..!!",
    "Tumhare paas koi band-aid hai? Kyunki tumhe dekhte hi main buri tarah gir pada hoon..!!",
    "Logon ko subah ki chai ki aadat hoti hai, lagta hai mujhe tumhari aadat hone wali hai..!!",
    "Hawa jab tumhari zulfon se guzarti hai, toh lagta hai woh bhi tumhari khushbu se jealous hai..!!",
    "Kya tum mujhe kuch der aur bina palke jhapkaye dekhne dogi? Mujhe apne doston ko batana hai ki pari kaisi dikhti hai..!!",
    "Aaj raat chand bhi badalon ke peeche chhup jayega, tumhara ye noor dekh kar..!!",
    "Tumhara naam WiFi hai kya? Kyunki mujhe tumse bina password ka ek strong connection feel ho raha hai..!!",
    "Meri life ki kitab ab tak thodi boring thi, kya tum iska sabse khoobsurat chapter banogi..!!"
]
